modLoader="javafml" 
loaderVersion="[37,)" 
license="All rights reserved"
[[mods]] 
modId="projectempire" 
version="${file.jarVersion}"
displayName="Project Empire" 
logoFile="examplemod.png" 
credits="Thanks for this example mod goes to Java" #optional
description='''
Mod by amitv
'''
[[dependencies.projectempire]] 
    modId="forge" 
    mandatory=true 
    versionRange="[37,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.projectempire]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
